name: Update Subscribe

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点自动运行
  workflow_dispatch:     # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Run merge script
      run: python merge_script.py  # 确保脚本在仓库中

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add bypass_subscribe.txt
        git commit -m "Auto-update subscription list"
        git push
